# Generated by Django 4.1.7 on 2023-04-06 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, null=True, unique=True, verbose_name='Гос номер')),
                ('brand', models.CharField(max_length=200, verbose_name='Марка')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('rudder_location', models.CharField(max_length=100, verbose_name='Расположение руля')),
                ('engine_volume', models.PositiveSmallIntegerField(verbose_name='Объем двигателя')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='SpecialMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Отметка')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_special_marks', to='cars.car')),
            ],
            options={
                'verbose_name': 'Особая отметка',
                'verbose_name_plural': 'Особые отметки',
            },
        ),
    ]
