# Generated by Django 4.1.7 on 2023-04-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodsOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(auto_now_add=True, verbose_name='От')),
                ('before_date', models.DateField(blank=True, null=True, verbose_name='До')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_periods_ownership', to='cars.car')),
            ],
            options={
                'verbose_name': 'Период владения',
                'verbose_name_plural': 'Периоды владения',
            },
        ),
    ]
